.changeset/great-singers-sparkle.md, packages/capsize/README.md, packages/capsize/package.json, packages/capsize/src/index.ts, site/src/components/Preview.tsx, yarn.lock
Provides a new utility `getCapHeight`, useful for determining the rendered cap height for a given font size. Also given [the recent information discovered](https://trac.webkit.org/wiki/LayoutUnit), deciding to round the precision of the CSS properties to 4 places.
=> Add getCapHeight utility & round decimal precision to 4 places

.changeset/quick-rabbits-cheat.md, .changeset/shaggy-comics-leave.md, packages/capsize/package.json, packages/capsize/src/index.ts, packages/capsize/src/renderToStyleRules.ts, packages/capsize/src/stories/tests.stories.ts, site/src/components/OutputCSS.tsx, yarn.lock
The styles object returned from `capsize` no longer contains a `padding` property (also removed the `height` property from the pseudo elements). This was previously used to prevent the negative margins from collapsing.
The technique has been swapped out in favour of using `display: table` on the pseudo elements, which also required an inversion of the negative margin direction.
```diff
{
"fontSize": "67.5165px",
"lineHeight": "72px",
-  "padding": "0.05px 0",
"::before": {
"content": "''",
+    "marginBottom": "-0.1648em",
+    "display": "table",
-    "marginTop": "-0.1648em",
-    "display": "block",
-    "height": 0
},
"::after": {
"content": "''",
+    "marginTop": "-0.1921em",
+    "display": "table",
-    "marginBottom": "-0.1921em",
-    "display": "block",
-    "height": 0
}
}
``` …
=> Change margin collapse guard from padding to display table

package.json
Disabling the husky install in CI to allow changesets to commit to the repo in CI.
[Husky docs](https://typicode.github.io/husky/#/?id=with-is-ci)
=> Disable husky install in CI

.changeset/wet-ads-confess.md, packages/metrics/scripts/build.ts, packages/unpack/README.md, packages/unpack/src/index.ts, site/src/components/AppStateContext.tsx, site/src/components/FontSelector/SystemFontSelector.tsx, site/src/components/MetricsPreview.tsx
The `fullName`, `postscriptName` and `subfamilyName` data fields were originally returned solely to support the website. These are no longer required, and looking to simplify this data structure in the lead up to version 1.
```diff
{
"familyName": "Abril Fatface",
-  "fullName": "Abril Fatface",
-  "postscriptName": "AbrilFatface-Regular",
-  "subfamilyName": "Regular",
"capHeight": 700,
"ascent": 1058,
"descent": -291,
"lineGap": 0,
"unitsPerEm": 1000,
"xHeight": 476
}
```
Also fixing an overflow cropping issue with certain fonts on the metrics preview panel.
=> Remove `fullName`, `postscriptName` and `subfamilyName` fields

.github/workflows/chromatic.yml
Providing the branch name to support Chromatic running against PRs from forks
[Chromatic options](https://www.chromatic.com/docs/cli#chromatic-options)
=> Chromatic: Specify branch name to support PRs from forks

.changeset/quiet-ducks-give.md, package.json, packages/unpack/package.json, packages/unpack/src/index.ts, site/gatsby-node.js, site/package.json, site/running-site-locally.md, yarn.lock
Upgrade `fontkit` to latest version. There is no change to the public API of unpack.
- Fontkit types package on definitely-typed is incorrect and doesnt model the breaking changes made in v2. Opened a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63204) and will update package when merged.
- Get site running locally on M1 macs
=> unpack: Upgrade fontkit

.changeset/wild-tables-argue.md, packages/metrics/package.json, packages/metrics/scripts/build.ts, packages/metrics/scripts/extractSystemFontMetrics.ts, packages/metrics/scripts/systemFonts.json
Provides metrics for the built in system font `Times New Roman`.
Can be used by importing as `@capsizecss/metrics/timesNewRoman`.
- Fixes order counting bug on the metrics build script
- Added script for extracting/updating system metrics. To run the script consumers require a directory locally with all the system fonts, and must set the `FONTS_DIRECTORY` env var with the path of the folder. Not expecting others to do this, but wanted to automate the process of updating these and cant commit the system files due to licenses on some of them.
=> Add `timesNewRoman` metrics

.changeset/clever-mangos-clap.md
No actual breaking change here, but cutting the v1 release to mark the packages moving out of experimental phase.
=> metrics, unpack: Cut v1 release

.changeset/thin-cows-think.md, .changeset/tricky-teachers-warn.md, packages/metrics/scripts/extractSystemFontMetrics.ts, packages/metrics/scripts/systemFonts.json, site/@types/detect-font.d.ts, site/src/components/FontSelector/SystemFontSelector.tsx
Expands the metrics library to include more system fonts. Fonts added are:
- `Tahoma`
- `Lucida Grande`
- `Verdana`
- `Trebuchet MS`
- `Georgia`
- `Courier New`
- `Brush Script`
The library now support all the [Best Web Safe Fonts](https://www.w3schools.com/cssref/css_websafe_fonts.php).
=> Add more system fonts

.github/workflows/release.yml, package.json
Running an install as part of the version process to fix lock file issues on Version Package PR.
```bash
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date
```
This makes the repo workflow consistent with our other packages/repos too.
=> Fix Changesets PR

.changeset/ninety-dodos-sparkle.md, .changeset/yellow-rings-exist.md, package.json, packages/metrics/README.md, packages/metrics/entireMetricsCollection/package.json, packages/metrics/package.json, packages/metrics/scripts/build.ts, packages/metrics/src/entireMetricsCollection.json, packages/metrics/src/entireMetricsCollection.ts, packages/metrics/src/index.ts, site/src/components/OutputCSS.tsx
Expose two new APIs: 
Provides the entire metrics collection as a JSON object, keyed by font family name.
**⚠️ CAUTION: Importing this will result in a _large JSON structure_ being pulled into your project! It is not recommended to use this client side.**
```ts
import { entireMetricsCollection } from '@capsizecss/metrics/entireMetricsCollection';
const metrics = entireMetricsCollection['arial'];
```
and
A helper function to support tooling that needs to convert the font family name to the correct casing for the relevant metrics import.
```ts
import { fontFamilyToCamelCase } from '@capsizecss/metrics';
const familyName = fontFamilyToCamelCase('--apple-system'); // => `appleSystem`
const metrics = await import(`@capsizecss/metrics/${familyName}`);
=> Expose new `entireMetricsCollection` and `fontFamilyToCamelCase` APIs

.changeset/gold-lions-study.md, packages/metrics/.npmignore, packages/metrics/package.json
With the last PR introducing new entrypoints and adding a `files` array to the `metrics` package, this saw all the generated metrics files be excluded from publishing.
Removing the files array to ensure everything gets published.
Tested with a snapshot published and installed into a code sandbox.
=> metrics: Ensure metrics files are published to npm

.changeset/wild-lemons-love.md, packages/core/src/createFontStack.test.ts, packages/core/src/createFontStack.ts
createFontStack: Apply metric overrides conditionally
Addresses an issue where metric overrides would be applied for fonts with the same metric values.
The `ascent-override`, `descent-override` and `line-gap-override` properties are now all conditional, only returned when the metrics differ between the preferred font and its fallback(s).
Fixes #136
=> createFontStack: Apply metric overrides conditionally

README.md
Adding a note to the readme to document the risk of applying layout-related styles to the same node as the capsize styles. 
This follows a few issues raised ([here](https://github.com/seek-oss/capsize/pull/132#issuecomment-1809317173) and [here](https://github.com/seek-oss/capsize/issues/15#issuecomment-663279448)) where the recommended solution would be to nest a separate node.
=> Add layout style collison warning to readme

.github/workflows/chromatic.yml, .github/workflows/preview-site.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/test.yml, package.json, packages/metrics/package.json, pnpm-lock.yaml
Upgrading the `pnpm/action-setup` GitHub action to move CI from node v12 to v16.
Other updates include:
- Switching `ts-node` over to `tsx` as the runner for TypeScript scripts.
- Updating `@manypkg/cli` to fix pnpm issue in CI
=> build: Update actions-setup and move to tsx

site/src/components/FAQs.tsx
`gap` in flexbox has been [widely supported](https://caniuse.com/flexbox-gap) for more than 2 years.
=> Remove mentions of partially supported flexbox gap

package.json
`pnpm deploy` is an built-in command, so our run-script needs to be run withy `pnpm run deploy`
=> Fix site deploy command

site/src/components/FAQs.tsx
Removes a duplicate `line-height` rule accidentally added in #160.
=> Fix CSS in FAQ

.changeset/clever-cobras-check.md, .changeset/sour-tools-crash.md, README.md, packages/core/src/createFontStack.test.ts, packages/core/src/createFontStack.ts
Two improvements to `createFontStack` API:
The `fontFamily` returned from `createFontStack` now includes the original fallback font name(s). These are appended to the end of the font stack in the case the preferred font and generated fallbacks are not available.
```ts
import lobster from '@capsizecss/metrics/lobster';
import arial from '@capsizecss/metrics/arial';
const { fontFamily } = createFontStack([
lobster,
arial,
]);
```
Where `fontFamily` is now:
```diff
- `Lobster, 'Lobster Fallback: Arial'`
+ `Lobster, 'Lobster Fallback: Arial', Arial`
```
---
Previously, when using `fontFaceFormat: 'styleObject'`, the generated fallback name  was not quoted as necessary within the `@font-face` declaration. This could cause issues if the font family name contained spaces or other characters that …
=> createFontStack: Add original fallback name & quote in declaration

.changeset/sour-files-tease.md, packages/vanilla-extract/package.json, packages/vanilla-extract/src/index.ts
Drop support for Vanilla Extract below v1.4
Upgrading to use Vanilla Extract's [style composition] API in favour of the long time deprecated `composeStyles` function.
There is no API change for Capsize consumers, but this change will require a peer dependency of `vanilla-extract@1.4.0` or greater.
[style composition]: https://vanilla-extract.style/documentation/api/style/#style-composition
=> vanilla-extract: Drop support for Vanilla Extract below v1.4

pnpm-lock.yaml, site/package.json, site/src/components/MetricsPreview.tsx
Introduce a new tab that makes metric viewing a first class part of the site. When selecting a font the default is still viewing measurements, but optionally a `JSON` tab is now available.
https://github.com/seek-oss/capsize/assets/912060/9e3f90c1-e47f-44ad-8058-2ca509bfd8d5
Closes https://github.com/seek-oss/capsize/issues/66
=> site: Add metrics viewer to site

.changeset/sweet-terms-clap.md, packages/metrics/package.json, packages/metrics/scripts/clean.ts, packages/metrics/scripts/generate.ts, site/vite.config.ts
metrics: Provide ESM entrypoints for individual font metrics
Build an ESM version of individual font metrics in preparation for adding named exports as part of the upcoming support for non-latin unicode subsets.
=> metrics: Provide ESM entrypoints for individual font metrics

.changeset/nasty-boats-flash.md, packages/metrics/scripts/googleFonts.json, packages/metrics/scripts/systemFonts.json, packages/metrics/src/entireMetricsCollection.json, packages/unpack/scripts/generate-weightings.ts
xWidthAvg: Improve metric by factoring in space to weightings
Analysing the `xWidthAvg` metrics for `latin` character sets, we have seen further improvement in the accuracy by factoring in the space character to the weightings.
=> xWidthAvg: Improve metric by factoring in space to weightings

.changeset/funny-trees-listen.md, packages/metrics/scripts/extract.ts, packages/metrics/scripts/googleFonts.json, packages/metrics/scripts/source-data/systemFontsData.ts, packages/metrics/scripts/systemFonts.json, packages/metrics/src/entireMetricsCollection.json
Ensure metrics are available using the public family name as seen on Google Fonts as opposed to the internal family name metric.
This makes sense as consumers are looking to import the metrics relevant to a specific system font or from Google Fonts (also aligns with the names Google use in their font declarations generated in the hosted stylesheets).
Previously, the metrics were imported with a path that used the internal family name, now they align with the font as seen on Google Fonts.
```diff
-import metrics from '@capsizecss/metrics/roundedMplus1c';
+import metrics from '@capsizecss/metrics/mPLUSRounded1c';
```
With only a small number of Google Fonts affected, this is only a break for the following fonts:
- Ballet
- Bodoni Moda
- Buda
- Bungee Spice
- Fjord One
- Geologica
- Imbue
- …
=> metrics: Prefer public family name to internal `familyName` metrics

.changeset/curvy-forks-brush.md, packages/metrics/scripts/source-data/systemFontsData.ts, packages/metrics/scripts/systemFonts.json
metrics: Update apple system font metrics
Previously the metrics provided for `-apple-system` and `BlinkMacSystemFont` were extracted from the `SF Pro` font, with a custom override to correct the `descent` metric.
Through work to support metrics for different font weights and styles, it was identified that MacOS uses the `SFNS` font.
Extracting the metrics from this font means no more custom overrides, and will now enable using this font as a fallback via postscript name soon too.
=> metrics: Update apple system font metrics

site/src/components/CapSizeSelector.tsx
Fixes a particularly annoying bug in the site since we [upgraded all the things](#160). By default, the Chakra `Slider` component will focus the thumb on change, meaning if you change the value in the text box, the focus shifts to the thumb.
Super annoying, easy fix 😄
=> site: Dont focus slider thumb on value change

.changeset/slimy-trees-design.md, packages/core/src/createFontStack.test.ts, packages/core/src/createFontStack.ts
Ensure that the `line-gap-override` property is applied correctly when overriding a fallback font with a web font that has no `lineGap`.
Previously if the override was zero it would be omitted from the declaration, rather than the correct behaviour of overriding the fallback metric to zero.
=> createFontStack: Apply `line-gap-override` with no `lineGap` in web font

.changeset/sour-mayflies-visit.md, packages/core/src/createFontStack.test.ts, packages/core/src/createFontStack.ts
Ensures a custom `size-adjust` value provided via the `fontFaceProperties` option is factored into the calculations for the metric overrides.
If a custom `size-adjust` value is provided:
```ts
createFontStack(
[ merriweatherSans, arial ],
{
fontFaceProperties: {
sizeAdjust: '300%'
}
},
)
```
The resulting metric overrides are now adjusted accordingly:
```diff
@font-face {
font-family: "Merriweather Sans Fallback";
src: local('Arial');
-  ascent-override: 92.3409%;
+  ascent-override: 32.8%;
-  descent-override: 25.619%;
+  descent-override: 9.1%;
line-gap-override: 0%;
size-adjust: 300%;
}
```
=> createFontStack: Ensure provided `size-adjust` is factored into overrides

.changeset/smart-sloths-hunt.md, packages/metrics/scripts/googleFonts.json, packages/metrics/scripts/source-data/googleFontsData.json
The New Google Font `Geist` is out, and it would be great to add support for it in `@capsize/metrics` as Next.js `next/font` is currently depending on it. 😌
=> Update Google Fonts

scripts/copy-readme.js
Following links from https://www.npmjs.com/package/@capsizecss/core sends me to 404 pages like https://github.com/seek-oss/capsize/blob/HEAD/packages/core/packages/metrics/README.md.
This PR extends the script copying the root's README to `packages/core` to rewrite relative links.
A local diff of the copied file (left: before, right: after):
=> Rewrite relative links when copying README

.changeset/brown-kings-design.md, packages/unpack/README.md, packages/unpack/src/index.ts, site/src/components/FAQs.tsx
Adds `fromBuffer`. We need this in Astro for [our fonts API](https://github.com/withastro/roadmap/pull/1039)
=> feat(unpack): fromBuffer

.changeset/kind-dingos-protect.md, packages/metrics/scripts/generate.ts, packages/metrics/scripts/googleFonts.json, packages/metrics/scripts/source-data/googleFontsData.json
Update Google Fonts to latest
Additionally, added support to the `generate` script to handle font names that start with a number (which TypeScript does not like). Does not affect external usage, but where required generated metric type names may be prefixed an underscore.
=> metrics: Update Google Fonts

.changeset/real-mails-repeat.md, packages/vanilla-extract/src/index.ts
I noticed that one of the typography styles in Braid's `Text` component contained a classname without a debug ID:
```
reset_base__1vaeyfc0
sprinkles_display_block_mobile__z3xxmb4z
typography_fontFamily__wvf7we0
typography_fontWeight_regular__wvf7we1
typography_tone_neutral__wvf7we21
typography_textSizeTrimmed_standard__wvf7wec
typography__wvf7web <---------------------------- THIS ONE
capsize_capsizeStyle__1u941fx4
typography_textSize_standard__wvf7wea
```
I believe this is the composed classname from the outer `style` call in `createTextStyle`. It doesn't automatically get a debug ID because Vanilla Extract's automatic debug ID generation only runs on `.css.*` files, but `createTextStyle` is inside an `index.mjs/cjs` file, so it gets missed. I assume this is why `debugId` is propagated …
=> `createTextStyle`: Correctly pass through `debugId` and remove redundant classname

README.md, package.json, pnpm-lock.yaml, site/scripts/deploy.js, site/src/components/layout.css
Resolves: https://github.com/seek-oss/capsize/actions/runs/18297627143/job/52099121572
Import assertions were removed in later node versions in favour of import attributes:
https://nodejs.org/docs/latest-v22.x/api/esm.html#import-attributes
Needed to also bump Prettier because it couldn't process the import attributes so that caused some other formatting changes
=> Switch import assertion to import attributes
